package club.inger.model1.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setComposeType(java.lang.String composeType) {
		set("compose_type", composeType);
	}

	public java.lang.String getComposeType() {
		return get("compose_type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCommentCount(java.lang.Long commentCount) {
		set("comment_count", commentCount);
	}

	public java.lang.Long getCommentCount() {
		return get("comment_count");
	}

	public void setNewsUniqueKey(java.lang.String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public java.lang.String getNewsUniqueKey() {
		return get("news_unique_key");
	}

	public void setCommentUniqueKey(java.lang.String commentUniqueKey) {
		set("comment_unique_key", commentUniqueKey);
	}

	public java.lang.String getCommentUniqueKey() {
		return get("comment_unique_key");
	}

	public void setUserUniqueKey(java.lang.String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public java.lang.String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setCommentTime(java.lang.String commentTime) {
		set("comment_time", commentTime);
	}

	public java.lang.String getCommentTime() {
		return get("comment_time");
	}

	public void setAcclaimCount(java.lang.Integer acclaimCount) {
		set("acclaim_count", acclaimCount);
	}

	public java.lang.Integer getAcclaimCount() {
		return get("acclaim_count");
	}

}
