package club.inger.model1.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsLogs<M extends BaseNewsLogs<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setNewsId(java.lang.Long newsId) {
		set("news_id", newsId);
	}

	public java.lang.Long getNewsId() {
		return get("news_id");
	}

	public void setViewTime(java.util.Date viewTime) {
		set("view_time", viewTime);
	}

	public java.util.Date getViewTime() {
		return get("view_time");
	}

	public void setPreferDegree(java.lang.Integer preferDegree) {
		set("prefer_degree", preferDegree);
	}

	public java.lang.Integer getPreferDegree() {
		return get("prefer_degree");
	}

	public void setUserUniqueKey(java.lang.String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public java.lang.String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setNewsUniqueKey(java.lang.String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public java.lang.String getNewsUniqueKey() {
		return get("news_unique_key");
	}

	public void setNewsTitle(java.lang.String newsTitle) {
		set("news_title", newsTitle);
	}

	public java.lang.String getNewsTitle() {
		return get("news_title");
	}

	public void setNewsType(java.lang.String newsType) {
		set("news_type", newsType);
	}

	public java.lang.String getNewsType() {
		return get("news_type");
	}

	public void setNewsUrl(java.lang.String newsUrl) {
		set("news_url", newsUrl);
	}

	public java.lang.String getNewsUrl() {
		return get("news_url");
	}

	public void setFeedbackContent(java.lang.String feedbackContent) {
		set("feedbackContent", feedbackContent);
	}

	public java.lang.String getFeedbackContent() {
		return get("feedbackContent");
	}

}
