package club.inger.model1.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReply<M extends BaseReply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCommentId(java.lang.Long commentId) {
		set("comment_id", commentId);
	}

	public java.lang.Long getCommentId() {
		return get("comment_id");
	}

	public void setReplyId(java.lang.Long replyId) {
		set("reply_id", replyId);
	}

	public java.lang.Long getReplyId() {
		return get("reply_id");
	}

	public void setReplyType(java.lang.Integer replyType) {
		set("reply_type", replyType);
	}

	public java.lang.Integer getReplyType() {
		return get("reply_type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setFromUid(java.lang.Long fromUid) {
		set("from_uid", fromUid);
	}

	public java.lang.Long getFromUid() {
		return get("from_uid");
	}

	public void setToUid(java.lang.Long toUid) {
		set("to_uid", toUid);
	}

	public java.lang.Long getToUid() {
		return get("to_uid");
	}

	public void setFromUKey(java.lang.String fromUKey) {
		set("from_u_key", fromUKey);
	}

	public java.lang.String getFromUKey() {
		return get("from_u_key");
	}

	public void setToUKey(java.lang.String toUKey) {
		set("to_u_key", toUKey);
	}

	public java.lang.String getToUKey() {
		return get("to_u_key");
	}

}
