package club.inger.model1.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZan<M extends BaseZan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTypeId(java.lang.String typeId) {
		set("type_id", typeId);
	}

	public java.lang.String getTypeId() {
		return get("type_id");
	}

	public void setAcclaimType(java.lang.Integer acclaimType) {
		set("acclaim_type", acclaimType);
	}

	public java.lang.Integer getAcclaimType() {
		return get("acclaim_type");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setAcclaimStatus(java.lang.Integer acclaimStatus) {
		set("acclaim_status", acclaimStatus);
	}

	public java.lang.Integer getAcclaimStatus() {
		return get("acclaim_status");
	}

	public void setAcclaimCount(java.lang.Long acclaimCount) {
		set("acclaim_count", acclaimCount);
	}

	public java.lang.Long getAcclaimCount() {
		return get("acclaim_count");
	}

	public void setUserUniqueKey(java.lang.String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public java.lang.String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setNewsUniqueKey(java.lang.String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public java.lang.String getNewsUniqueKey() {
		return get("news_unique_key");
	}

	public void setCommentUniqueKey(java.lang.String commentUniqueKey) {
		set("comment_unique_key", commentUniqueKey);
	}

	public java.lang.String getCommentUniqueKey() {
		return get("comment_unique_key");
	}

}
