package club.inger.model1.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsModules<M extends BaseNewsModules<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setModulesName(java.lang.String modulesName) {
		set("modules_name", modulesName);
	}

	public java.lang.String getModulesName() {
		return get("modules_name");
	}

}
