package club.inger.model1.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollect<M extends BaseCollect<M>> extends Model<M> implements IBean {

	public void setCollectTime(java.util.Date collectTime) {
		set("collect_time", collectTime);
	}

	public java.util.Date getCollectTime() {
		return get("collect_time");
	}

	public void setNewsUrl(java.lang.String newsUrl) {
		set("news_url", newsUrl);
	}

	public java.lang.String getNewsUrl() {
		return get("news_url");
	}

	public void setNewsType(java.lang.String newsType) {
		set("news_type", newsType);
	}

	public java.lang.String getNewsType() {
		return get("news_type");
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserUniqueKey(java.lang.String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public java.lang.String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setNewsUniqueKey(java.lang.String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public java.lang.String getNewsUniqueKey() {
		return get("news_unique_key");
	}

}
