package club.inger.model1;

import club.inger.model1.base.BaseCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collect extends BaseCollect<Collect> {
	public static final Collect dao = new Collect().dao();
}
