package club.inger.model1;

import club.inger.model1.base.BaseReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reply extends BaseReply<Reply> {
	public static final Reply dao = new Reply().dao();
}
