package club.inger.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollect<M extends BaseCollect<M>> extends Model<M> implements IBean {

	public void setCollectTime(java.util.Date collectTime) {
		set("collect_time", collectTime);
	}

	public java.util.Date getCollectTime() {
		return get("collect_time");
	}

	public void setNewsUrl(String newsUrl) {
		set("news_url", newsUrl);
	}

	public String getNewsUrl() {
		return get("news_url");
	}

	public void setNewsType(String newsType) {
		set("news_type", newsType);
	}

	public String getNewsType() {
		return get("news_type");
	}

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setUserUniqueKey(String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setNewsUniqueKey(String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public String getNewsUniqueKey() {
		return get("news_unique_key");
	}

}
