package club.inger.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReply<M extends BaseReply<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCommentId(Long commentId) {
		set("comment_id", commentId);
	}

	public Long getCommentId() {
		return get("comment_id");
	}

	public void setReplyId(Long replyId) {
		set("reply_id", replyId);
	}

	public Long getReplyId() {
		return get("reply_id");
	}

	public void setReplyType(Integer replyType) {
		set("reply_type", replyType);
	}

	public Integer getReplyType() {
		return get("reply_type");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setFromUid(Long fromUid) {
		set("from_uid", fromUid);
	}

	public Long getFromUid() {
		return get("from_uid");
	}

	public void setToUid(Long toUid) {
		set("to_uid", toUid);
	}

	public Long getToUid() {
		return get("to_uid");
	}

	public void setFromUKey(String fromUKey) {
		set("from_u_key", fromUKey);
	}

	public String getFromUKey() {
		return get("from_u_key");
	}

	public void setToUKey(String toUKey) {
		set("to_u_key", toUKey);
	}

	public String getToUKey() {
		return get("to_u_key");
	}

}
