package club.inger.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsLogs<M extends BaseNewsLogs<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setUserId(Long userId) {
		set("user_id", userId);
	}

	public Long getUserId() {
		return get("user_id");
	}

	public void setNewsId(Long newsId) {
		set("news_id", newsId);
	}

	public Long getNewsId() {
		return get("news_id");
	}

	public void setViewTime(java.util.Date viewTime) {
		set("view_time", viewTime);
	}

	public java.util.Date getViewTime() {
		return get("view_time");
	}

	public void setPreferDegree(Integer preferDegree) {
		set("prefer_degree", preferDegree);
	}

	public Integer getPreferDegree() {
		return get("prefer_degree");
	}

	public void setUserUniqueKey(String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setNewsUniqueKey(String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public String getNewsUniqueKey() {
		return get("news_unique_key");
	}

	public void setNewsTitle(String newsTitle) {
		set("news_title", newsTitle);
	}

	public String getNewsTitle() {
		return get("news_title");
	}

	public void setNewsType(String newsType) {
		set("news_type", newsType);
	}

	public String getNewsType() {
		return get("news_type");
	}

	public void setNewsUrl(String newsUrl) {
		set("news_url", newsUrl);
	}

	public String getNewsUrl() {
		return get("news_url");
	}

}
