package club.inger.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setComposeType(String composeType) {
		set("compose_type", composeType);
	}

	public String getComposeType() {
		return get("compose_type");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCommentCount(Long commentCount) {
		set("comment_count", commentCount);
	}

	public Long getCommentCount() {
		return get("comment_count");
	}

	public void setNewsUniqueKey(String newsUniqueKey) {
		set("news_unique_key", newsUniqueKey);
	}

	public String getNewsUniqueKey() {
		return get("news_unique_key");
	}

	public void setCommentUniqueKey(String commentUniqueKey) {
		set("comment_unique_key", commentUniqueKey);
	}

	public String getCommentUniqueKey() {
		return get("comment_unique_key");
	}

	public void setUserUniqueKey(String userUniqueKey) {
		set("user_unique_key", userUniqueKey);
	}

	public String getUserUniqueKey() {
		return get("user_unique_key");
	}

	public void setCommentTime(String commentTime) {
		set("comment_time", commentTime);
	}

	public String getCommentTime() {
		return get("comment_time");
	}

	public void setAcclaimCount(Integer acclaimCount) {
		set("acclaim_count", acclaimCount);
	}

	public Integer getAcclaimCount() {
		return get("acclaim_count");
	}

}
