package club.inger.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsModules<M extends BaseNewsModules<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setModulesName(String modulesName) {
		set("modules_name", modulesName);
	}

	public String getModulesName() {
		return get("modules_name");
	}

}
