package club.inger.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setPrefList(String prefList) {
		set("pref_list", prefList);
	}

	public String getPrefList() {
		return get("pref_list");
	}

	public void setLatestLogTime(java.util.Date latestLogTime) {
		set("latest_log_time", latestLogTime);
	}

	public java.util.Date getLatestLogTime() {
		return get("latest_log_time");
	}

	public void setUserName(String userName) {
		set("user_name", userName);
	}

	public String getUserName() {
		return get("user_name");
	}

	public void setImageType(Integer imageType) {
		set("image_type", imageType);
	}

	public Integer getImageType() {
		return get("image_type");
	}

	public void setUniqueKey(String uniqueKey) {
		set("unique_key", uniqueKey);
	}

	public String getUniqueKey() {
		return get("unique_key");
	}

	public void setWhereFrom(String whereFrom) {
		set("where_from", whereFrom);
	}

	public String getWhereFrom() {
		return get("where_from");
	}
	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return get("latitude");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return get("longitude");
	}

}
