package club.inger.model;

import club.inger.model.base.BaseNewsLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsLogs extends BaseNewsLogs<NewsLogs> {
	public static final NewsLogs dao = new NewsLogs().dao();
}
