package club.inger.model;

import club.inger.model.base.BaseNewsModules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsModules extends BaseNewsModules<NewsModules> {
	public static final NewsModules dao = new NewsModules().dao();
}
