package club.inger.model;

import club.inger.model.base.BaseRecommendations;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recommendations extends BaseRecommendations<Recommendations> {
	public static final Recommendations dao = new Recommendations().dao();
}
