package club.inger.model;

import club.inger.model.base.BaseUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Users extends BaseUsers<Users> {
	public static final Users dao = new Users().dao();
}
