package club.inger.model;

import club.inger.model.base.BaseZan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zan extends BaseZan<Zan> {
	public static final Zan dao = new Zan().dao();
}
